// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA72qZlRiFFqxtiVNZdVgQzM3jS-8oa1SY',
    appId: '1:595666415182:web:ee69a1091e4bf110f91d1f',
    messagingSenderId: '595666415182',
    projectId: 'flutter-tec-chat',
    authDomain: 'flutter-tec-chat.firebaseapp.com',
    storageBucket: 'flutter-tec-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfDWtHTciryWveMS0Rv8WJeS_Ll7ZrsM4',
    appId: '1:595666415182:ios:68d5e8c902b431f0f91d1f',
    messagingSenderId: '595666415182',
    projectId: 'flutter-tec-chat',
    storageBucket: 'flutter-tec-chat.firebasestorage.app',
    iosBundleId: 'com.example.flutterTecChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfDWtHTciryWveMS0Rv8WJeS_Ll7ZrsM4',
    appId: '1:595666415182:ios:68d5e8c902b431f0f91d1f',
    messagingSenderId: '595666415182',
    projectId: 'flutter-tec-chat',
    storageBucket: 'flutter-tec-chat.firebasestorage.app',
    iosBundleId: 'com.example.flutterTecChat',
  );
}
